-- Enable pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- Drop tables if they exist
DROP TABLE IF EXISTS checkout_velocity;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS calendar;

-- Create products table
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    image_url TEXT,
    product_url TEXT,
    tags TEXT[] NOT NULL DEFAULT '{}',
    zip_codes TEXT[] NOT NULL DEFAULT '{}', -- Localized availability (empty means global)
    embedding vector(512) -- 512-dimensional vector for CLIP embeddings
);

-- Create calendar table
CREATE TABLE calendar (
    zip_code TEXT NOT NULL,
    date DATE NOT NULL,
    event_name TEXT NOT NULL,
    event_type TEXT NOT NULL DEFAULT 'festival', -- 'festival', 'pre_wedding', 'wedding_day', 'post_wedding'
    attire_tags TEXT[] NOT NULL DEFAULT '{}',
    is_festive BOOLEAN DEFAULT TRUE,
    PRIMARY KEY (zip_code, date)
);

-- Create Hybrid Recommendation PostgreSQL Function
CREATE OR REPLACE FUNCTION get_hybrid_recommendations(
    user_vibe vector(512),
    trending_tags TEXT[],
    is_cold_wave BOOLEAN,
    is_festive_season BOOLEAN,
    target_event_tags TEXT[],
    is_wedding_day BOOLEAN,
    target_zip_code TEXT
)
RETURNS TABLE (
    id BIGINT,
    name TEXT,
    description TEXT,
    image_url TEXT,
    product_url TEXT,
    tags TEXT[],
    vector_score FLOAT,
    tag_score FLOAT,
    final_score FLOAT
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        p.id, 
        p.name, 
        p.description,
        p.image_url,
        p.product_url,
        p.tags,
        
        -- Cosine similarity: 1 - cosine distance (<=>). Range: [0, 2] distance, so similarity is [ -1, 1 ].
        -- We clamp it to [0, 1] for normalization.
        COALESCE(1.0 - (p.embedding <=> user_vibe), 0.0)::FLOAT AS vector_score,
        
        -- Score based on tag intersections with trending YouTube tags AND active event tags
        (
            SELECT COALESCE(COUNT(*)::FLOAT, 0.0) 
            FROM unnest(p.tags) AS pt 
            WHERE pt = ANY(trending_tags) OR pt = ANY(target_event_tags)
        )::FLOAT AS tag_score,
        
        -- Overall hybrid score:
        -- 40% Visual Vibe similarity
        -- 30% Youtube Trending tag match / Event tag match
        -- 30% Climate/Festive/Wedding boosts
        (
            (COALESCE(1.0 - (p.embedding <=> user_vibe), 0.0) * 0.4) + 
            ((SELECT COALESCE(COUNT(*)::FLOAT, 0.0) FROM unnest(p.tags) AS pt WHERE pt = ANY(trending_tags) OR pt = ANY(target_event_tags)) * 0.3) +
            
            -- Climate boost
            (CASE WHEN is_cold_wave AND 'winter' = ANY(p.tags) THEN 0.15 ELSE 0.0 END) +
            
            -- Festive boost
            (CASE WHEN is_festive_season AND 'festive' = ANY(p.tags) THEN 0.15 ELSE 0.0 END) +
            
            -- Event/Wedding boost
            (CASE WHEN is_wedding_day AND 'ceremonial' = ANY(p.tags) THEN 0.3 ELSE 0.0 END) +
            (CASE WHEN array_length(target_event_tags, 1) > 0 AND p.tags && target_event_tags THEN 0.15 ELSE 0.0 END)
        )::FLOAT AS final_score
    FROM products p
    WHERE (p.zip_codes = '{}' OR target_zip_code = ANY(p.zip_codes))
    ORDER BY final_score DESC;
END;
$$ LANGUAGE plpgsql;

-- Seed Calendar Events for Patna (800008)
INSERT INTO calendar (zip_code, date, event_name, event_type, attire_tags, is_festive) VALUES
('800008', '2026-11-11', 'Chitragupta Puja & Bhai Dooj', 'festival', '{"ethnic", "festive", "traditional", "pink", "red", "yellow"}', true),
('800008', '2026-11-13', 'Chhath Puja (Nahay Khay)', 'festival', '{"cotton", "saree", "traditional", "yellow", "white", "patna"}', true),
('800008', '2026-11-14', 'Chhath Puja (Kharna)', 'festival', '{"cotton", "saree", "traditional", "yellow", "white", "patna"}', true),
('800008', '2026-11-15', 'Chhath Puja (Sandhya Arghya)', 'festival', '{"saree", "cotton", "traditional", "dhoti", "saffron", "yellow", "white", "patna", "chhath-puja"}', true),
('800008', '2026-11-16', 'Chhath Puja (Usha Arghya)', 'festival', '{"saree", "cotton", "traditional", "dhoti", "saffron", "yellow", "white", "patna", "chhath-puja"}', true),
('800008', '2026-10-04', 'Jitiya (Jivitputrika Vrat)', 'festival', '{"saree", "ethnic", "traditional", "red", "maroon"}', true),
('800008', '2026-03-22', 'Bihar Diwas (Bihar Day)', 'festival', '{"saree", "salwar", "bhagalpuri-silk", "kurta", "dhoti", "nehru-jacket", "white", "cream", "patna"}', true),
('800008', '2026-04-23', 'Veer Kunwar Singh Jayanti', 'festival', '{"kurta", "white", "cream"}', true),
('800008', '2026-01-24', 'Karpoori Thakur Jayanti', 'festival', '{"shawl", "warm", "winter", "jacket", "white"}', true),
('800008', '2026-10-21', 'Shri Krishna Singh Jayanti', 'festival', '{"saree", "salwar", "kurta", "white", "beige"}', true),
('800008', '2026-03-26', 'Emperor Ashoka Ashtami', 'festival', '{"cotton", "saree", "suit", "white", "pastel"}', true),
('800008', '2026-01-03', 'Prakash Parv (Patna Sahib Gurudwara)', 'festival', '{"traditional", "white", "blue", "saffron"}', true),
('800008', '2026-02-02', 'Saraswati Puja (Vasant Panchami)', 'festival', '{"saree", "kurta", "yellow", "ethnic"}', true),
('800008', '2026-08-10', 'Shravani Mela Pilgrim Cycle', 'festival', '{"saffron", "dhoti"}', true),
-- Patna Wedding Scenario presets
('800008', '2026-12-09', 'Patna Pre-Wedding (Haldi Ceremony)', 'pre_wedding', '{"cotton", "yellow", "saffron", "ethnic"}', true),
('800008', '2026-12-10', 'Patna Wedding Day (Pheras Ritual)', 'wedding_day', '{"heavy_silk", "traditional_embroidery", "ceremonial", "silk", "saree", "sherwani", "crimson", "gold", "maroon"}', true),
('800008', '2026-12-11', 'Patna Post-Wedding (Vidaai Ceremony)', 'post_wedding', '{"festive", "magenta", "fuchsia", "gold", "ethnic"}', true);

-- Seed Calendar Events for Kochi (682001)
INSERT INTO calendar (zip_code, date, event_name, event_type, attire_tags, is_festive) VALUES
('682001', '2026-08-27', 'Onam Festival (Thiruvonam)', 'festival', '{"saree", "mundu", "kasavu_weave", "white", "cream", "gold"}', true),
('682001', '2026-04-14', 'Vishu (New Year)', 'festival', '{"ethnic", "yellow", "gold", "cream"}', true),
('682001', '2026-04-03', 'Good Friday Church Service', 'festival', '{"modest", "formal", "premium", "white"}', false),
('682001', '2026-04-05', 'Easter Sunday Celebration', 'festival', '{"modest", "formal", "premium", "pastel"}', true),
('682001', '2026-09-12', 'Synagogue Rosh Hashanah Festival', 'festival', '{"subtle", "modest", "premium", "elegant"}', true),
('682001', '2026-01-15', 'Makaravilakku Sabarimala Devotional', 'festival', '{"black", "saffron", "traditional", "mundu", "dhoti"}', false),
('682001', '2026-01-25', 'Chandanakudam Festival (Mosque)', 'festival', '{"traditional", "Islamic", "modest", "ethnic", "embroidered"}', true),
('682001', '2026-12-28', 'Indira Gandhi Boat Race Carnival', 'festival', '{"casual", "breathable", "cotton", "coastal"}', true),
('682001', '2026-12-31', 'Cochin Carnival New Years Eve', 'festival', '{"vibrant", "party", "bohemian", "modern"}', true),
('682001', '2026-01-20', 'Kochi-Muziris Biennale (Art Peak)', 'festival', '{"artsy", "bohemian", "linen", "sustainable", "modern"}', true),
-- Kochi Wedding Scenario presets
('682001', '2026-12-26', 'Kochi Pre-Wedding (Nischayam)', 'pre_wedding', '{"semi-ethnic", "mint", "peach", "lavender", "pastel"}', true),
('682001', '2026-12-27', 'Kochi Wedding Day (Thalikettu)', 'wedding_day', '{"kasavu_weave", "off-white", "cream", "gold"}', true),
('682001', '2026-12-29', 'Kochi Post-Wedding (Reception)', 'post_wedding', '{"contemporary_fusion", "royal-blue", "wine", "black", "silver"}', true);

-- Seed Calendar Events for Shillong (793003)
INSERT INTO calendar (zip_code, date, event_name, event_type, attire_tags, is_festive) VALUES
('793003', '2026-11-15', 'Shillong Cherry Blossom Fest', 'festival', '{"streetwear", "jacket", "coat", "scarf", "boots"}', true),
('793003', '2026-12-25', 'Christmas Day Celebration', 'festival', '{"velvet", "woolen", "dress", "formal", "winter"}', true),
('793003', '2026-04-15', 'Shad Suk Mynsiem Harvest Fest', 'festival', '{"jainsem", "jymphong", "traditional", "ethnic", "silk"}', true),
('793003', '2026-10-25', 'Shillong Autumn Festival', 'festival', '{"indie", "fusion", "denim-fusion", "streetwear"}', true),
('793003', '2026-11-10', 'Wangala Festival (100 Drums)', 'festival', '{"traditional", "tribal_heritage", "headgear", "accessories"}', true),
('793003', '2026-07-14', 'Behdiengkhlam Festival Rituals', 'festival', '{"traditional"}', true),
-- Shillong Wedding Scenario presets
('793003', '2026-12-19', 'Shillong Pre-Wedding (Pynhiar Synjat)', 'pre_wedding', '{"western_formal", "silver", "white", "pastel", "fusion"}', true),
('793003', '2026-12-20', 'Shillong Wedding Day (Traditional)', 'wedding_day', '{"handwoven_silk", "tribal_heritage", "jainsem", "jymphong", "earth-tones"}', true),
('793003', '2026-12-21', 'Shillong Post-Wedding (Reception)', 'post_wedding', '{"western_formal", "navy", "burgundy", "black", "metallic"}', true);

-- Universal Civic, Academic & Social Velocity Events (Regional Variations)
INSERT INTO calendar (zip_code, date, event_name, event_type, attire_tags, is_festive) VALUES
-- 1. Republic Day (Jan 26)
('800008', '2026-01-26', 'Republic Day Parade', 'festival', '{"white", "saffron", "green", "ethnic", "formal"}', true),
('682001', '2026-01-26', 'Republic Day Parade', 'festival', '{"white", "fusion", "formal", "lightweight"}', true),
('793003', '2026-01-26', 'Republic Day Parade', 'festival', '{"white", "saffron", "green", "winter", "jacket", "formal"}', true),

-- 2. Holi (Mar 3)
('800008', '2026-03-03', 'Holi Festival of Colors', 'festival', '{"white", "cotton", "casual", "dailywear"}', true),
('682001', '2026-03-03', 'Holi Festival of Colors', 'festival', '{"casual", "streetwear", "denim", "cotton"}', true),
('793003', '2026-03-03', 'Holi Festival of Colors', 'festival', '{"hoodie", "winter", "warm", "streetwear"}', true),

-- 3. Good Friday / Easter (Apr 5)
('800008', '2026-04-05', 'Easter Sunday Service', 'festival', '{"ethnic", "formal", "modest", "pastel"}', true),
('793003', '2026-04-05', 'Easter Sunday Service', 'festival', '{"western_formal", "navy", "black", "grey", "suit", "gown"}', true),

-- 4. Eid-ul-Fitr (Mar 20)
('800008', '2026-03-20', 'Eid-ul-Fitr Celebration', 'festival', '{"ethnic", "festive", "traditional_embroidery", "embroidered", "kurta", "sherwani"}', true),
('682001', '2026-03-20', 'Eid-ul-Fitr Celebration', 'festival', '{"ethnic", "festive", "modest", "elegant"}', true),
('793003', '2026-03-20', 'Eid-ul-Fitr Celebration', 'festival', '{"western_formal", "modest", "fusion"}', true),

-- 5. Independence Day (Aug 15)
('800008', '2026-08-15', 'Independence Day Ceremony', 'festival', '{"saffron", "white", "green", "ethnic", "formal", "cotton"}', true),
('682001', '2026-08-15', 'Independence Day Ceremony', 'festival', '{"saffron", "white", "green", "ethnic", "formal", "lightweight"}', true),
('793003', '2026-08-15', 'Independence Day Ceremony', 'festival', '{"saffron", "white", "green", "formal", "jacket", "layered"}', true),

-- 6. Durga Puja (Oct 18)
('800008', '2026-10-18', 'Durga Puja Peak Pandals', 'festival', '{"ethnic", "festive", "silk", "saree", "heavy_silk", "traditional"}', true),
('682001', '2026-10-18', 'Durga Puja Celebrations', 'festival', '{"ethnic", "festive", "minimalist", "cotton"}', true),
('793003', '2026-10-18', 'Durga Puja Autumn Fusion', 'festival', '{"streetwear", "fusion", "modern"}', true),

-- 7. Diwali (Nov 8)
('800008', '2026-11-08', 'Diwali Lights Festival', 'festival', '{"ethnic", "festive", "traditional", "regal", "gold", "silk"}', true),
('682001', '2026-11-08', 'Diwali Lights Festival', 'festival', '{"ethnic", "festive", "contemporary_fusion", "fusion", "earth-tones"}', true),
('793003', '2026-11-08', 'Diwali Festival of Lights', 'festival', '{"winter", "warm", "jacket", "velvet", "festive"}', true),

-- 8. Christmas Day (Dec 25)
('800008', '2026-12-25', 'Christmas Day Celebrations', 'festival', '{"winter", "party", "jacket", "velvet", "warm"}', true),
('682001', '2026-12-25', 'Christmas Day Celebrations', 'festival', '{"vibrant", "party", "bohemian", "modern", "western"}', true),

-- 9. College Farewells (Apr 10)
('800008', '2026-04-10', 'College Farewell Gala', 'festival', '{"formal", "saree", "suit", "ethnic"}', true),
('682001', '2026-04-10', 'College Farewell Gala', 'festival', '{"pastel", "fusion", "cotton", "lightweight"}', true),
('793003', '2026-04-10', 'College Farewell Gala', 'festival', '{"western_formal", "navy", "black", "grey", "blazer", "suit"}', true),

-- 10. Graduation / Annual (May 15)
('800008', '2026-05-15', 'Annual Convocation Ceremony', 'festival', '{"formal", "ethnic", "fusion"}', true),
('682001', '2026-05-15', 'Annual Convocation Ceremony', 'festival', '{"formal", "elegant", "premium"}', true),
('793003', '2026-05-15', 'Annual Convocation Ceremony', 'festival', '{"western_formal", "suit", "gown", "blazer"}', true),

-- 11. Annual School Day (Dec 5)
('800008', '2026-12-05', 'Annual School Day Celebration', 'festival', '{"formal", "smart_casual", "ethnic"}', true),
('682001', '2026-12-05', 'Annual School Day Celebration', 'festival', '{"formal", "smart_casual", "ethnic"}', true),
('793003', '2026-12-05', 'Annual School Day Celebration', 'festival', '{"formal", "smart_casual", "ethnic"}', true),

-- 12. Back-to-College (Jul 5)
('800008', '2026-07-05', 'Back-to-College Opening', 'festival', '{"casual", "streetwear", "cotton", "breathable"}', false),
('682001', '2026-07-05', 'Back-to-College Opening', 'festival', '{"casual", "streetwear", "linen", "breathable"}', false),
('793003', '2026-07-05', 'Back-to-College Opening', 'festival', '{"casual", "streetwear", "jacket", "coat", "winter"}', false),

-- 13. College Fests (Feb 15)
('800008', '2026-02-15', 'Annual College Fest', 'festival', '{"indie", "streetwear", "denim", "graphic"}', true),
('682001', '2026-02-15', 'Annual College Fest', 'festival', '{"indie", "streetwear", "denim", "graphic"}', true),
('793003', '2026-02-15', 'Annual College Fest', 'festival', '{"indie", "streetwear", "denim", "graphic"}', true),

-- 14. Wedding Guest Day (Nov 25)
('800008', '2026-11-25', 'Wedding Guest Ceremony', 'festival', '{"ethnic", "festive", "silk", "velvet", "traditional"}', true),
('682001', '2026-11-25', 'Wedding Guest Ceremony', 'festival', '{"ethnic", "festive", "silk", "velvet", "traditional"}', true),
('793003', '2026-11-25', 'Wedding Guest Ceremony', 'festival', '{"ethnic", "festive", "silk", "velvet", "traditional"}', true),

-- 15. Office Ethnic Day (Sep 4)
('800008', '2026-09-04', 'Office Ethnic Day', 'festival', '{"ethnic", "subtle", "pastel", "minimalist", "kurta", "saree"}', true),
('682001', '2026-09-04', 'Office Ethnic Day', 'festival', '{"ethnic", "subtle", "pastel", "minimalist", "kurta", "saree"}', true),
('793003', '2026-09-04', 'Office Ethnic Day', 'festival', '{"ethnic", "subtle", "pastel", "minimalist", "kurta", "saree"}', true),

-- 16. College Admissions (Jul 15)
('800008', '2026-07-15', 'College Admissions Season', 'festival', '{"smart_casual", "breathable_cotton", "modest_fusion", "summer_wear"}', false),
('682001', '2026-07-15', 'College Admissions Season', 'festival', '{"monsoon_ready", "contemporary_casual", "dark_tones", "minimalist"}', false),
('793003', '2026-07-15', 'College Admissions Season', 'festival', '{"streetwear", "light_layers", "western_casual", "trendy_youth"}', false);

-- ============================================================
-- CHECKOUT VELOCITY TABLE (Real-Time Purchase Pulse)
-- ============================================================
-- Tracks simulated real-time purchase velocity per product per zip code.
-- A high velocity_score means the item is "going viral" in that region.

CREATE TABLE checkout_velocity (
    product_id BIGINT NOT NULL,
    zip_code TEXT NOT NULL,
    velocity_score FLOAT NOT NULL DEFAULT 0.0, -- 0.0 to 1.0 normalized
    units_last_hour INT NOT NULL DEFAULT 0,
    last_updated TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (product_id, zip_code)
);

-- Seed Checkout Velocity: Patna (800008)
-- Simulating: Red Banarasi sarees and sherwanis going viral during wedding season
INSERT INTO checkout_velocity (product_id, zip_code, velocity_score, units_last_hour) VALUES
(1, '800008', 0.92, 47),   -- Crimson Banarasi Silk Saree: VIRAL
(2, '800008', 0.88, 38),   -- Maroon Designer Sherwani: HOT
(7, '800008', 0.75, 22),   -- Chhath Puja Saffron Dhoti Set
(9, '800008', 0.65, 18),   -- Saraswati Puja Yellow Saree
(13, '800008', 0.70, 20),  -- Jitiya Vrat Red Saree
(15, '800008', 0.80, 30),  -- Embellished Wedding Chunri: HIGH
(11, '800008', 0.55, 12),  -- Tricolour Fusion Nehru Jacket
(48, '800008', 0.60, 15),  -- Heavy Velvet Kurta Suit
(6, '800008', 0.72, 24);   -- Bhagalpuri Silk Saree

-- Seed Checkout Velocity: Kochi (682001)
-- Simulating: Kasavu sarees dominating during Onam season
INSERT INTO checkout_velocity (product_id, zip_code, velocity_score, units_last_hour) VALUES
(16, '682001', 0.95, 52),  -- Premium Kasavu Wedding Saree: VIRAL
(17, '682001', 0.85, 35),  -- Kasavu Zari Mundu Set: HOT
(25, '682001', 0.78, 28),  -- Vishu Golden Kasavu Kurti
(28, '682001', 0.70, 20),  -- Gold Border Kasavu Dupatta
(20, '682001', 0.62, 16),  -- Kochi Biennale Linen Shirt
(26, '682001', 0.55, 11),  -- Easter Sunday Modest Dress
(23, '682001', 0.50, 9),   -- Coastal Boat Race Casuals
(24, '682001', 0.58, 14),  -- Cochin Carnival Party Tee
(30, '682001', 0.45, 7);   -- Artsy Asymmetrical Kurta

-- Seed Checkout Velocity: Shillong (793003)
-- Simulating: Winter streetwear and tribal heritage pieces trending
INSERT INTO checkout_velocity (product_id, zip_code, velocity_score, units_last_hour) VALUES
(31, '793003', 0.90, 42),  -- [Khasi Weaves] Silk Jainsem: VIRAL
(32, '793003', 0.82, 32),  -- [Boutique Jymphong] Maroon Vest: HOT
(33, '793003', 0.78, 26),  -- [Hillcrest] Designer Jainsem
(36, '793003', 0.72, 22),  -- Cherry Blossom Suede Jacket
(37, '793003', 0.68, 19),  -- Velvet Christmas Maxi Dress
(41, '793003', 0.65, 17),  -- Woolen Cable Knit Cardigan
(44, '793003', 0.60, 14),  -- Indie Streetwear Fleece Hoodie
(40, '793003', 0.55, 10),  -- Avant-Garde Denim Trench
(39, '793003', 0.75, 25);  -- Shad Suk Ryndia Shawl

-- ============================================================
-- OUTFIT COMPLETER TABLE (Cross-Category Look Completer Mapping)
-- ============================================================
-- Links clothing items to completing accessories and footwear for specific occasions.

CREATE TABLE outfit_completer (
    primary_item_id BIGINT NOT NULL,
    suggested_accessory_id BIGINT,
    suggested_footwear_id BIGINT,
    occasion_tag TEXT NOT NULL,
    PRIMARY KEY (primary_item_id, occasion_tag)
);

-- Seed Look Completer mappings
INSERT INTO outfit_completer (primary_item_id, suggested_accessory_id, suggested_footwear_id, occasion_tag) VALUES
-- Patna Wedding Pheras (Crimson Banarasi Silk Saree -> Kundan Necklace + Traditional heels)
(1, 286, 334, 'wedding_day'),
-- Patna Wedding Sherwani -> Kundan Necklace/Stole + Mojris/Traditional footwear
(2, 286, 334, 'wedding_day'),
-- Saraswati Puja Yellow Saree -> Anklets + Sandals
(9, 292, 334, 'festival'),
-- Chhath Puja Saree -> Anklets
(7, 292, NULL, 'festival'),
-- Onam Kasavu Saree -> Golden jewellery/Anklets
(16, 292, NULL, 'festival'),
-- Kochi Wedding Kasavu Saree -> Kundan Jewelry + Traditional footwear
(97, 286, 334, 'wedding_day'),
-- Shillong Cherry Blossom Fest -> Beaded Vest/Scarf + Ankle boots
(110, 38, 334, 'festival'),
-- Christmas Day Velvet Dress -> Pearl Jewelry + Boots
(112, 307, 334, 'festival');

-- ============================================================
-- REGIONAL BOUTIQUE TRENDS TABLE (Micro-Trends)
-- ============================================================
CREATE TABLE IF NOT EXISTS regional_boutique_trends (
    store_id VARCHAR(50) PRIMARY KEY,
    zip_code VARCHAR(10),
    locality VARCHAR(100),
    store_name VARCHAR(100),
    social_signal_source VARCHAR(50),
    simulated_engagement INT,
    extracted_visual_trend VARCHAR(50),
    style_vibe_cluster VARCHAR(50)
);

